baseURL = "http://fjord.jp/"
languageCode = "ja"
title = "FJORD,LLC"
theme = "fjord-2017"
disqusShortname = "fjord"
publishDir = "docs"

[params]
  stylesheet = "/assets/application.css"
  javascript = "/assets/application.js"
  name = "FJORD,LLC"
  japanese_name = "合同会社フィヨルド"
  copyright = "FJORD,LLC"
  github = "https://github.com/rakuishi/"
  amazon = "https://github.com/rakuishi/"
  analytics = "UA-2927688-6"
